export type RequestData = (typeof requestData)[number];
export const requestData = [
  {
    Date: "2025-08-01 10:12:04",
    Status: 200,
    Method: "GET",
    Pathname: "/",
    Latency: 51,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 0,
    "timing-phase.tls": 10,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 23,
    "timing-phase.transfer": 9,
  },
  {
    Date: "2025-08-05 12:47:16",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api",
    Latency: 62,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 14,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 11,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 31,
  },
  {
    Date: "2025-08-04 02:49:07",
    Status: 429,
    Method: "PATCH",
    Pathname: "/api/auth/login",
    Latency: 39,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 4,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 9,
    "timing-phase.transfer": 13,
  },
  {
    Date: "2025-08-03 07:44:29",
    Status: 200,
    Method: "DELETE",
    Pathname: "/api/users",
    Latency: 74,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 11,
    "timing-phase.tls": 9,
    "timing-phase.ttfb": 12,
    "timing-phase.connection": 21,
    "timing-phase.transfer": 21,
  },
  {
    Date: "2025-08-01 19:21:37",
    Status: 404,
    Method: "PUT",
    Pathname: "/",
    Latency: 50,
    "region.shortname": "ord",
    "region.fullname": "Chicago",
    "timing-phase.dns": 5,
    "timing-phase.tls": 9,
    "timing-phase.ttfb": 5,
    "timing-phase.connection": 24,
    "timing-phase.transfer": 7,
  },
  {
    Date: "2025-08-06 02:08:38",
    Status: 200,
    Method: "DELETE",
    Pathname: "/metrics",
    Latency: 63,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 2,
    "timing-phase.tls": 12,
    "timing-phase.ttfb": 6,
    "timing-phase.connection": 22,
    "timing-phase.transfer": 21,
  },
  {
    Date: "2025-08-04 09:37:14",
    Status: 200,
    Method: "POST",
    Pathname: "/api/orders",
    Latency: 20,
    "region.shortname": "ord",
    "region.fullname": "Chicago",
    "timing-phase.dns": 5,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 4,
    "timing-phase.connection": 2,
    "timing-phase.transfer": 7,
  },
  {
    Date: "2025-07-30 08:40:06",
    Status: 404,
    Method: "GET",
    Pathname: "/api/users/6933",
    Latency: 73,
    "region.shortname": "lhr",
    "region.fullname": "London",
    "timing-phase.dns": 26,
    "timing-phase.tls": 7,
    "timing-phase.ttfb": 16,
    "timing-phase.connection": 15,
    "timing-phase.transfer": 9,
  },
  {
    Date: "2025-08-10 02:00:57",
    Status: 200,
    Method: "GET",
    Pathname: "/api/users",
    Latency: 51,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 12,
    "timing-phase.tls": 10,
    "timing-phase.ttfb": 13,
    "timing-phase.connection": 6,
    "timing-phase.transfer": 10,
  },
  {
    Date: "2025-08-01 09:22:07",
    Status: 200,
    Method: "PATCH",
    Pathname: "/healthz",
    Latency: 42,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 5,
    "timing-phase.tls": 1,
    "timing-phase.ttfb": 7,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 25,
  },
  {
    Date: "2025-07-30 13:04:33",
    Status: 201,
    Method: "PATCH",
    Pathname: "/api/products/4211",
    Latency: 90,
    "region.shortname": "lhr",
    "region.fullname": "London",
    "timing-phase.dns": 4,
    "timing-phase.tls": 44,
    "timing-phase.ttfb": 17,
    "timing-phase.connection": 14,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-07-29 19:56:37",
    Status: 200,
    Method: "POST",
    Pathname: "/api/orders",
    Latency: 139,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 12,
    "timing-phase.tls": 30,
    "timing-phase.ttfb": 48,
    "timing-phase.connection": 31,
    "timing-phase.transfer": 18,
  },
  {
    Date: "2025-08-07 11:55:51",
    Status: 200,
    Method: "GET",
    Pathname: "/api/auth/refresh",
    Latency: 56,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 1,
    "timing-phase.tls": 18,
    "timing-phase.ttfb": 11,
    "timing-phase.connection": 5,
    "timing-phase.transfer": 21,
  },
  {
    Date: "2025-08-03 08:43:42",
    Status: 200,
    Method: "GET",
    Pathname: "/api",
    Latency: 98,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 11,
    "timing-phase.tls": 15,
    "timing-phase.ttfb": 35,
    "timing-phase.connection": 26,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-08-04 23:53:16",
    Status: 200,
    Method: "DELETE",
    Pathname: "/api/users/2173",
    Latency: 117,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 40,
    "timing-phase.tls": 3,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 61,
  },
  {
    Date: "2025-08-08 18:41:33",
    Status: 403,
    Method: "DELETE",
    Pathname: "/content/articles",
    Latency: 56,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 16,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 22,
    "timing-phase.connection": 10,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-08-11 14:25:54",
    Status: 200,
    Method: "GET",
    Pathname: "/api/users/8636",
    Latency: 65,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 14,
    "timing-phase.tls": 17,
    "timing-phase.ttfb": 17,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 9,
  },
  {
    Date: "2025-08-03 09:15:39",
    Status: 404,
    Method: "POST",
    Pathname: "/content/articles/spicy-camera",
    Latency: 66,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 11,
    "timing-phase.tls": 9,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 29,
  },
  {
    Date: "2025-08-07 08:50:33",
    Status: 200,
    Method: "GET",
    Pathname: "/metrics",
    Latency: 83,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 4,
    "timing-phase.tls": 18,
    "timing-phase.ttfb": 26,
    "timing-phase.connection": 20,
    "timing-phase.transfer": 15,
  },
  {
    Date: "2025-08-03 22:23:33",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/users/1599",
    Latency: 124,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 32,
    "timing-phase.tls": 10,
    "timing-phase.ttfb": 15,
    "timing-phase.connection": 32,
    "timing-phase.transfer": 35,
  },
  {
    Date: "2025-07-29 20:03:54",
    Status: 200,
    Method: "DELETE",
    Pathname: "/",
    Latency: 99,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 32,
    "timing-phase.tls": 19,
    "timing-phase.ttfb": 11,
    "timing-phase.connection": 12,
    "timing-phase.transfer": 25,
  },
  {
    Date: "2025-08-02 15:14:22",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api",
    Latency: 101,
    "region.shortname": "ord",
    "region.fullname": "Chicago",
    "timing-phase.dns": 18,
    "timing-phase.tls": 11,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 59,
  },
  {
    Date: "2025-08-07 17:25:01",
    Status: 201,
    Method: "PATCH",
    Pathname: "/api/auth/refresh",
    Latency: 44,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 2,
    "timing-phase.tls": 1,
    "timing-phase.ttfb": 23,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 10,
  },
  {
    Date: "2025-08-06 23:54:12",
    Status: 200,
    Method: "POST",
    Pathname: "/metrics",
    Latency: 74,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 1,
    "timing-phase.tls": 20,
    "timing-phase.ttfb": 28,
    "timing-phase.connection": 15,
    "timing-phase.transfer": 10,
  },
  {
    Date: "2025-08-08 21:50:56",
    Status: 200,
    Method: "POST",
    Pathname: "/api",
    Latency: 103,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 28,
    "timing-phase.tls": 10,
    "timing-phase.ttfb": 22,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 39,
  },
  {
    Date: "2025-08-11 16:28:05",
    Status: 200,
    Method: "GET",
    Pathname: "/api/auth/refresh",
    Latency: 54,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 17,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 16,
    "timing-phase.connection": 9,
    "timing-phase.transfer": 7,
  },
  {
    Date: "2025-08-05 12:25:46",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/users",
    Latency: 51,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 5,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 13,
    "timing-phase.connection": 16,
    "timing-phase.transfer": 12,
  },
  {
    Date: "2025-07-29 22:32:49",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/users/8416",
    Latency: 66,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 3,
    "timing-phase.tls": 22,
    "timing-phase.ttfb": 14,
    "timing-phase.connection": 22,
    "timing-phase.transfer": 5,
  },
  {
    Date: "2025-08-02 08:20:05",
    Status: 200,
    Method: "PUT",
    Pathname: "/content/articles",
    Latency: 88,
    "region.shortname": "lhr",
    "region.fullname": "London",
    "timing-phase.dns": 10,
    "timing-phase.tls": 37,
    "timing-phase.ttfb": 18,
    "timing-phase.connection": 11,
    "timing-phase.transfer": 12,
  },
  {
    Date: "2025-08-06 18:06:18",
    Status: 201,
    Method: "DELETE",
    Pathname: "/api/products",
    Latency: 32,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 7,
    "timing-phase.tls": 3,
    "timing-phase.ttfb": 4,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 14,
  },
  {
    Date: "2025-08-08 02:08:55",
    Status: 200,
    Method: "GET",
    Pathname: "/api/products/8187",
    Latency: 32,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 3,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 6,
    "timing-phase.connection": 7,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-08-01 15:31:22",
    Status: 200,
    Method: "PUT",
    Pathname: "/",
    Latency: 64,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 12,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 17,
    "timing-phase.connection": 27,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-08-08 06:22:01",
    Status: 400,
    Method: "GET",
    Pathname: "/search",
    Latency: 71,
    "region.shortname": "ord",
    "region.fullname": "Chicago",
    "timing-phase.dns": 2,
    "timing-phase.tls": 25,
    "timing-phase.ttfb": 17,
    "timing-phase.connection": 20,
    "timing-phase.transfer": 7,
  },
  {
    Date: "2025-08-07 16:56:28",
    Status: 404,
    Method: "PUT",
    Pathname: "/api/orders/4207",
    Latency: 97,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 10,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 32,
    "timing-phase.connection": 22,
    "timing-phase.transfer": 31,
  },
  {
    Date: "2025-07-31 18:43:37",
    Status: 200,
    Method: "DELETE",
    Pathname: "/metrics",
    Latency: 146,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 6,
    "timing-phase.tls": 0,
    "timing-phase.ttfb": 87,
    "timing-phase.connection": 28,
    "timing-phase.transfer": 25,
  },
  {
    Date: "2025-08-04 01:14:40",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/products",
    Latency: 25,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 2,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 3,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-07-30 01:44:45",
    Status: 200,
    Method: "GET",
    Pathname: "/api/orders",
    Latency: 37,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 9,
    "timing-phase.tls": 13,
    "timing-phase.ttfb": 12,
    "timing-phase.connection": 1,
    "timing-phase.transfer": 2,
  },
  {
    Date: "2025-07-31 13:03:51",
    Status: 204,
    Method: "GET",
    Pathname: "/metrics",
    Latency: 22,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 5,
    "timing-phase.tls": 4,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 1,
    "timing-phase.transfer": 4,
  },
  {
    Date: "2025-08-06 12:15:44",
    Status: 200,
    Method: "PATCH",
    Pathname: "/healthz",
    Latency: 38,
    "region.shortname": "fra",
    "region.fullname": "Frankfurt",
    "timing-phase.dns": 4,
    "timing-phase.tls": 3,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 2,
    "timing-phase.transfer": 21,
  },
  {
    Date: "2025-08-08 16:39:59",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api",
    Latency: 43,
    "region.shortname": "yyz",
    "region.fullname": "Toronto",
    "timing-phase.dns": 5,
    "timing-phase.tls": 6,
    "timing-phase.ttfb": 16,
    "timing-phase.connection": 12,
    "timing-phase.transfer": 4,
  },
  {
    Date: "2025-08-10 14:40:52",
    Status: 200,
    Method: "POST",
    Pathname: "/api/orders/8579",
    Latency: 54,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 23,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 9,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-08-07 23:00:39",
    Status: 200,
    Method: "GET",
    Pathname: "/api/products/1650",
    Latency: 91,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 9,
    "timing-phase.tls": 19,
    "timing-phase.ttfb": 26,
    "timing-phase.connection": 13,
    "timing-phase.transfer": 24,
  },
  {
    Date: "2025-08-05 18:46:05",
    Status: 503,
    Method: "DELETE",
    Pathname: "/api/users",
    Latency: 95,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 11,
    "timing-phase.tls": 35,
    "timing-phase.ttfb": 11,
    "timing-phase.connection": 14,
    "timing-phase.transfer": 24,
  },
  {
    Date: "2025-08-05 19:59:25",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/auth/refresh",
    Latency: 76,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 20,
    "timing-phase.tls": 9,
    "timing-phase.ttfb": 13,
    "timing-phase.connection": 19,
    "timing-phase.transfer": 15,
  },
  {
    Date: "2025-08-06 08:59:01",
    Status: 200,
    Method: "GET",
    Pathname: "/api/orders/8056",
    Latency: 32,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 1,
    "timing-phase.tls": 1,
    "timing-phase.ttfb": 6,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 16,
  },
  {
    Date: "2025-08-09 17:47:51",
    Status: 200,
    Method: "POST",
    Pathname: "/api/auth/refresh",
    Latency: 72,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 15,
    "timing-phase.tls": 19,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 18,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-08-03 16:57:29",
    Status: 200,
    Method: "POST",
    Pathname: "/api/users/3234",
    Latency: 58,
    "region.shortname": "fra",
    "region.fullname": "Frankfurt",
    "timing-phase.dns": 10,
    "timing-phase.tls": 12,
    "timing-phase.ttfb": 15,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 13,
  },
  {
    Date: "2025-08-06 08:10:57",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/orders",
    Latency: 57,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 3,
    "timing-phase.tls": 20,
    "timing-phase.ttfb": 21,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 9,
  },
  {
    Date: "2025-08-10 06:11:31",
    Status: 500,
    Method: "PATCH",
    Pathname: "/content/articles/modern-notebook",
    Latency: 76,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 13,
    "timing-phase.tls": 19,
    "timing-phase.ttfb": 21,
    "timing-phase.connection": 5,
    "timing-phase.transfer": 18,
  },
  {
    Date: "2025-08-07 13:05:47",
    Status: 401,
    Method: "DELETE",
    Pathname: "/content/articles/vintage-camera",
    Latency: 27,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 5,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 2,
    "timing-phase.connection": 6,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-07-31 08:57:30",
    Status: 200,
    Method: "PATCH",
    Pathname: "/content/articles/modern-camera",
    Latency: 89,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 38,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 31,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 8,
  },
  {
    Date: "2025-08-11 15:35:02",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/products/513",
    Latency: 65,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 13,
    "timing-phase.tls": 31,
    "timing-phase.ttfb": 3,
    "timing-phase.connection": 13,
    "timing-phase.transfer": 5,
  },
  {
    Date: "2025-08-11 06:13:29",
    Status: 201,
    Method: "POST",
    Pathname: "/search",
    Latency: 57,
    "region.shortname": "ord",
    "region.fullname": "Chicago",
    "timing-phase.dns": 1,
    "timing-phase.tls": 15,
    "timing-phase.ttfb": 7,
    "timing-phase.connection": 19,
    "timing-phase.transfer": 15,
  },
  {
    Date: "2025-08-08 00:00:11",
    Status: 502,
    Method: "POST",
    Pathname: "/search",
    Latency: 68,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 6,
    "timing-phase.tls": 17,
    "timing-phase.ttfb": 25,
    "timing-phase.connection": 7,
    "timing-phase.transfer": 13,
  },
  {
    Date: "2025-08-01 16:29:38",
    Status: 401,
    Method: "DELETE",
    Pathname: "/api/products/6893",
    Latency: 95,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 23,
    "timing-phase.tls": 25,
    "timing-phase.ttfb": 26,
    "timing-phase.connection": 15,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-08-09 19:42:10",
    Status: 400,
    Method: "PATCH",
    Pathname: "/healthz",
    Latency: 54,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 27,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 14,
    "timing-phase.connection": 10,
    "timing-phase.transfer": 1,
  },
  {
    Date: "2025-08-10 22:41:42",
    Status: 204,
    Method: "PATCH",
    Pathname: "/metrics",
    Latency: 104,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 15,
    "timing-phase.tls": 10,
    "timing-phase.ttfb": 26,
    "timing-phase.connection": 29,
    "timing-phase.transfer": 24,
  },
  {
    Date: "2025-08-08 03:22:24",
    Status: 200,
    Method: "PATCH",
    Pathname: "/content/articles",
    Latency: 158,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 15,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 75,
    "timing-phase.connection": 7,
    "timing-phase.transfer": 56,
  },
  {
    Date: "2025-08-09 11:03:32",
    Status: 201,
    Method: "POST",
    Pathname: "/",
    Latency: 57,
    "region.shortname": "lhr",
    "region.fullname": "London",
    "timing-phase.dns": 3,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 6,
    "timing-phase.connection": 14,
    "timing-phase.transfer": 29,
  },
  {
    Date: "2025-08-05 13:36:47",
    Status: 404,
    Method: "DELETE",
    Pathname: "/api/auth/refresh",
    Latency: 76,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 2,
    "timing-phase.tls": 21,
    "timing-phase.ttfb": 5,
    "timing-phase.connection": 30,
    "timing-phase.transfer": 18,
  },
  {
    Date: "2025-08-09 19:53:41",
    Status: 400,
    Method: "POST",
    Pathname: "/search",
    Latency: 111,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 7,
    "timing-phase.tls": 34,
    "timing-phase.ttfb": 47,
    "timing-phase.connection": 9,
    "timing-phase.transfer": 14,
  },
  {
    Date: "2025-08-10 12:30:11",
    Status: 200,
    Method: "DELETE",
    Pathname: "/content/articles/vintage-chair",
    Latency: 37,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 10,
    "timing-phase.tls": 3,
    "timing-phase.ttfb": 14,
    "timing-phase.connection": 1,
    "timing-phase.transfer": 9,
  },
  {
    Date: "2025-08-03 18:29:20",
    Status: 200,
    Method: "GET",
    Pathname: "/content/articles/fast-lantern",
    Latency: 148,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 35,
    "timing-phase.tls": 9,
    "timing-phase.ttfb": 64,
    "timing-phase.connection": 23,
    "timing-phase.transfer": 17,
  },
  {
    Date: "2025-08-11 11:18:46",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/orders/8795",
    Latency: 56,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 5,
    "timing-phase.tls": 18,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 3,
    "timing-phase.transfer": 22,
  },
  {
    Date: "2025-08-08 06:30:15",
    Status: 400,
    Method: "DELETE",
    Pathname: "/api/products/9391",
    Latency: 293,
    "region.shortname": "fra",
    "region.fullname": "Frankfurt",
    "timing-phase.dns": 157,
    "timing-phase.tls": 51,
    "timing-phase.ttfb": 24,
    "timing-phase.connection": 31,
    "timing-phase.transfer": 30,
  },
  {
    Date: "2025-08-09 16:38:22",
    Status: 200,
    Method: "POST",
    Pathname: "/api",
    Latency: 188,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 69,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 64,
    "timing-phase.connection": 6,
    "timing-phase.transfer": 47,
  },
  {
    Date: "2025-07-31 20:10:52",
    Status: 204,
    Method: "GET",
    Pathname: "/content/articles/modern-lantern",
    Latency: 43,
    "region.shortname": "fra",
    "region.fullname": "Frankfurt",
    "timing-phase.dns": 4,
    "timing-phase.tls": 11,
    "timing-phase.ttfb": 14,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 6,
  },
  {
    Date: "2025-08-06 13:02:28",
    Status: 200,
    Method: "GET",
    Pathname: "/content/articles/modern-notebook",
    Latency: 38,
    "region.shortname": "lhr",
    "region.fullname": "London",
    "timing-phase.dns": 6,
    "timing-phase.tls": 11,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 6,
    "timing-phase.transfer": 7,
  },
  {
    Date: "2025-08-03 14:28:40",
    Status: 200,
    Method: "DELETE",
    Pathname: "/api",
    Latency: 130,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 10,
    "timing-phase.tls": 27,
    "timing-phase.ttfb": 36,
    "timing-phase.connection": 20,
    "timing-phase.transfer": 37,
  },
  {
    Date: "2025-07-29 06:22:54",
    Status: 201,
    Method: "PATCH",
    Pathname: "/api/users/2611",
    Latency: 97,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 28,
    "timing-phase.tls": 14,
    "timing-phase.ttfb": 6,
    "timing-phase.connection": 31,
    "timing-phase.transfer": 18,
  },
  {
    Date: "2025-08-02 01:57:02",
    Status: 204,
    Method: "POST",
    Pathname: "/api/orders/3228",
    Latency: 55,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 0,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 17,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 32,
  },
  {
    Date: "2025-08-08 21:49:01",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/auth/login",
    Latency: 272,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 43,
    "timing-phase.tls": 39,
    "timing-phase.ttfb": 103,
    "timing-phase.connection": 14,
    "timing-phase.transfer": 73,
  },
  {
    Date: "2025-08-08 14:23:59",
    Status: 200,
    Method: "GET",
    Pathname: "/api/auth/refresh",
    Latency: 70,
    "region.shortname": "yyz",
    "region.fullname": "Toronto",
    "timing-phase.dns": 13,
    "timing-phase.tls": 22,
    "timing-phase.ttfb": 22,
    "timing-phase.connection": 5,
    "timing-phase.transfer": 8,
  },
  {
    Date: "2025-07-30 14:32:54",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/products",
    Latency: 59,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 11,
    "timing-phase.tls": 15,
    "timing-phase.ttfb": 10,
    "timing-phase.connection": 2,
    "timing-phase.transfer": 21,
  },
  {
    Date: "2025-08-02 04:58:02",
    Status: 200,
    Method: "POST",
    Pathname: "/api/auth/refresh",
    Latency: 76,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 3,
    "timing-phase.tls": 15,
    "timing-phase.ttfb": 28,
    "timing-phase.connection": 15,
    "timing-phase.transfer": 15,
  },
  {
    Date: "2025-08-08 17:36:41",
    Status: 200,
    Method: "DELETE",
    Pathname: "/metrics",
    Latency: 68,
    "region.shortname": "yyz",
    "region.fullname": "Toronto",
    "timing-phase.dns": 7,
    "timing-phase.tls": 1,
    "timing-phase.ttfb": 24,
    "timing-phase.connection": 18,
    "timing-phase.transfer": 18,
  },
  {
    Date: "2025-08-09 16:41:48",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/products/3900",
    Latency: 23,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 5,
    "timing-phase.tls": 1,
    "timing-phase.ttfb": 1,
    "timing-phase.connection": 2,
    "timing-phase.transfer": 14,
  },
  {
    Date: "2025-08-04 11:48:30",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/products",
    Latency: 100,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 11,
    "timing-phase.tls": 10,
    "timing-phase.ttfb": 29,
    "timing-phase.connection": 16,
    "timing-phase.transfer": 34,
  },
  {
    Date: "2025-07-29 19:25:56",
    Status: 401,
    Method: "DELETE",
    Pathname: "/api/users",
    Latency: 40,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 2,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 31,
    "timing-phase.connection": 0,
    "timing-phase.transfer": 2,
  },
  {
    Date: "2025-08-09 05:01:15",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/users",
    Latency: 79,
    "region.shortname": "ord",
    "region.fullname": "Chicago",
    "timing-phase.dns": 7,
    "timing-phase.tls": 9,
    "timing-phase.ttfb": 23,
    "timing-phase.connection": 25,
    "timing-phase.transfer": 15,
  },
  {
    Date: "2025-08-07 03:25:10",
    Status: 200,
    Method: "POST",
    Pathname: "/api/auth/refresh",
    Latency: 48,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 5,
    "timing-phase.tls": 5,
    "timing-phase.ttfb": 13,
    "timing-phase.connection": 7,
    "timing-phase.transfer": 18,
  },
  {
    Date: "2025-08-07 20:11:14",
    Status: 200,
    Method: "GET",
    Pathname: "/api/auth/login",
    Latency: 50,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 6,
    "timing-phase.tls": 19,
    "timing-phase.ttfb": 10,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-07-29 16:31:48",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/orders/5956",
    Latency: 140,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 15,
    "timing-phase.tls": 56,
    "timing-phase.ttfb": 35,
    "timing-phase.connection": 17,
    "timing-phase.transfer": 17,
  },
  {
    Date: "2025-08-09 12:40:41",
    Status: 429,
    Method: "POST",
    Pathname: "/api",
    Latency: 109,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 8,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 35,
    "timing-phase.connection": 11,
    "timing-phase.transfer": 53,
  },
  {
    Date: "2025-08-09 18:43:12",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/orders/2507",
    Latency: 24,
    "region.shortname": "yyz",
    "region.fullname": "Toronto",
    "timing-phase.dns": 6,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 4,
    "timing-phase.connection": 3,
    "timing-phase.transfer": 9,
  },
  {
    Date: "2025-08-10 13:48:24",
    Status: 200,
    Method: "POST",
    Pathname: "/search",
    Latency: 50,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 6,
    "timing-phase.tls": 16,
    "timing-phase.ttfb": 10,
    "timing-phase.connection": 13,
    "timing-phase.transfer": 5,
  },
  {
    Date: "2025-07-31 23:51:12",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/users/4733",
    Latency: 24,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 1,
    "timing-phase.tls": 3,
    "timing-phase.ttfb": 10,
    "timing-phase.connection": 2,
    "timing-phase.transfer": 8,
  },
  {
    Date: "2025-07-31 23:21:38",
    Status: 200,
    Method: "GET",
    Pathname: "/api/auth/login",
    Latency: 33,
    "region.shortname": "hkg",
    "region.fullname": "Hong Kong",
    "timing-phase.dns": 1,
    "timing-phase.tls": 4,
    "timing-phase.ttfb": 8,
    "timing-phase.connection": 15,
    "timing-phase.transfer": 5,
  },
  {
    Date: "2025-08-05 20:42:45",
    Status: 200,
    Method: "PATCH",
    Pathname: "/api/users",
    Latency: 59,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 3,
    "timing-phase.tls": 1,
    "timing-phase.ttfb": 15,
    "timing-phase.connection": 29,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-07-29 22:52:20",
    Status: 200,
    Method: "POST",
    Pathname: "/api",
    Latency: 29,
    "region.shortname": "sfo",
    "region.fullname": "San Francisco",
    "timing-phase.dns": 4,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 9,
    "timing-phase.connection": 6,
    "timing-phase.transfer": 2,
  },
  {
    Date: "2025-08-05 12:40:55",
    Status: 200,
    Method: "PATCH",
    Pathname: "/search",
    Latency: 104,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 12,
    "timing-phase.tls": 18,
    "timing-phase.ttfb": 37,
    "timing-phase.connection": 16,
    "timing-phase.transfer": 21,
  },
  {
    Date: "2025-08-01 01:07:13",
    Status: 400,
    Method: "POST",
    Pathname: "/api/users",
    Latency: 48,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 9,
    "timing-phase.tls": 2,
    "timing-phase.ttfb": 15,
    "timing-phase.connection": 8,
    "timing-phase.transfer": 14,
  },
  {
    Date: "2025-08-02 10:05:32",
    Status: 200,
    Method: "PATCH",
    Pathname: "/content/articles/spicy-notebook",
    Latency: 46,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 1,
    "timing-phase.tls": 6,
    "timing-phase.ttfb": 4,
    "timing-phase.connection": 28,
    "timing-phase.transfer": 7,
  },
  {
    Date: "2025-08-05 15:29:10",
    Status: 200,
    Method: "PUT",
    Pathname: "/",
    Latency: 45,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 1,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 26,
    "timing-phase.connection": 7,
    "timing-phase.transfer": 3,
  },
  {
    Date: "2025-08-06 05:56:36",
    Status: 404,
    Method: "DELETE",
    Pathname: "/api/auth/login",
    Latency: 90,
    "region.shortname": "yyz",
    "region.fullname": "Toronto",
    "timing-phase.dns": 12,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 47,
    "timing-phase.connection": 7,
    "timing-phase.transfer": 16,
  },
  {
    Date: "2025-08-10 04:16:29",
    Status: 403,
    Method: "POST",
    Pathname: "/",
    Latency: 52,
    "region.shortname": "syd",
    "region.fullname": "Sydney",
    "timing-phase.dns": 15,
    "timing-phase.tls": 8,
    "timing-phase.ttfb": 12,
    "timing-phase.connection": 6,
    "timing-phase.transfer": 11,
  },
  {
    Date: "2025-08-11 09:34:50",
    Status: 200,
    Method: "GET",
    Pathname: "/api/users/5997",
    Latency: 94,
    "region.shortname": "sin",
    "region.fullname": "Singapore",
    "timing-phase.dns": 2,
    "timing-phase.tls": 18,
    "timing-phase.ttfb": 33,
    "timing-phase.connection": 4,
    "timing-phase.transfer": 37,
  },
  {
    Date: "2025-08-02 00:48:48",
    Status: 404,
    Method: "PUT",
    Pathname: "/api/auth/login",
    Latency: 100,
    "region.shortname": "iad",
    "region.fullname": "Washington, D.C.",
    "timing-phase.dns": 28,
    "timing-phase.tls": 15,
    "timing-phase.ttfb": 13,
    "timing-phase.connection": 28,
    "timing-phase.transfer": 16,
  },
  {
    Date: "2025-07-30 16:01:08",
    Status: 200,
    Method: "GET",
    Pathname: "/content/articles/fast-scooter",
    Latency: 86,
    "region.shortname": "fra",
    "region.fullname": "Frankfurt",
    "timing-phase.dns": 17,
    "timing-phase.tls": 3,
    "timing-phase.ttfb": 13,
    "timing-phase.connection": 27,
    "timing-phase.transfer": 26,
  },
  {
    Date: "2025-08-04 20:31:09",
    Status: 200,
    Method: "PUT",
    Pathname: "/api/orders",
    Latency: 82,
    "region.shortname": "nyc",
    "region.fullname": "New York City",
    "timing-phase.dns": 4,
    "timing-phase.tls": 0,
    "timing-phase.ttfb": 42,
    "timing-phase.connection": 26,
    "timing-phase.transfer": 10,
  },
];
